"""Added time from and timeTo in String

Revision ID: 5acfa0f1bb5d
Revises: d780c7feb09a
Create Date: 2023-11-29 00:18:38.554363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5acfa0f1bb5d'
down_revision = 'd780c7feb09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('time_from',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('time_to',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('time_to',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
        batch_op.alter_column('time_from',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
