"""Changed not to delete cascade

Revision ID: 96127f78d6ce
Revises: 15c640684a7c
Create Date: 2023-11-13 19:10:48.641691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96127f78d6ce'
down_revision = '15c640684a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint('notes_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notes_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
