"""Added time from and timeTo

Revision ID: d780c7feb09a
Revises: 96127f78d6ce
Create Date: 2023-11-29 00:06:26.884489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd780c7feb09a'
down_revision = '96127f78d6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_from', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('time_to', sa.Time(), nullable=True))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('time_to')
        batch_op.drop_column('time_from')

    # ### end Alembic commands ###
